### ISSUE TITLE
SSP - Crash on death

### ISSUE THREAD

**Issue by HellishINC** [OneLemonyBoi/MiniUtilities#38] opened 2021-05-19 01:32 UTC
Was shot by skeleton and died. As soon as the "respawn" button appears the game hangs for 5-10 seconds and then crashes. So far it seems this repeatable 100% of the time as 5 out of 5 deaths resulted in the same.

Tested on both JDK8 and 11.

Full crash log: https://paste.ee/p/JRajz

```
[18:16:58] [Server thread/INFO] [minecraft/MinecraftServer]: hellishinc was shot by Skeleton
[18:16:58] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3083/0x0000000800d90c40@1e7ca56a
		2: ASM: class net.silentchaos512.gear.event.GearEvents onXpDrop(Lnet/minecraftforge/event/entity/living/LivingExperienceDropEvent;)V
		3: ASM: class com.simibubi.create.content.contraptions.components.deployer.DeployerFakePlayer deployerKillsDoNotSpawnXP(Lnet/minecraftforge/event/entity/living/LivingExperienceDropEvent;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$3083/0x0000000800d90c40@7110edca
		5: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.ChallengerParticles@60bdd53a registerEvent(Lnet/minecraftforge/event/entity/EntityEvent;)V
		6: LOWEST
		7: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@1638421f onExperienceDrop(Lnet/minecraftforge/event/entity/living/LivingExperienceDropEvent;)V
java.lang.NullPointerException
	at onelemonyboi.miniutilities.items.enchantments.ExperienceHarvesterHandler.handleEntityKill(ExperienceHarvesterHandler.java:15)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:234)
	at net.minecraft.entity.LivingEntity.func_226294_cV_(LivingEntity.java:1260)
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntity.java:1246)
	at net.minecraft.entity.player.ServerPlayerEntity.func_70645_a(ServerPlayerEntity.java:514)
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1059)
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:814)
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:597)
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326)
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118)
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188)
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:829)

[18:16:58] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 55ceffc2-ad93-4189-86f5-6d4f442f1b97
[18:16:58] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] hellishinc was shot by Skeleton
[18:16:58] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}
Caused by: java.lang.NullPointerException
	at onelemonyboi.miniutilities.items.enchantments.ExperienceHarvesterHandler.handleEntityKill(ExperienceHarvesterHandler.java:15) ~[miniutilities:1.1.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:234) ~[forge:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_226294_cV_(LivingEntity.java:1260) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:the_bumblezone.mixins.json:entities.LivingEntityMixin,pl:mixin:APP:environmental.mixins.json:LivingEntityMixin,pl:mixin:APP:allurement.mixins.json:LivingEntityAccessor,pl:mixin:APP:allurement.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:neapolitan.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntity.java:1246) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:the_bumblezone.mixins.json:entities.LivingEntityMixin,pl:mixin:APP:environmental.mixins.json:LivingEntityMixin,pl:mixin:APP:allurement.mixins.json:LivingEntityAccessor,pl:mixin:APP:allurement.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:neapolitan.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70645_a(ServerPlayerEntity.java:514) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1059) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:the_bumblezone.mixins.json:entities.LivingEntityMixin,pl:mixin:APP:environmental.mixins.json:LivingEntityMixin,pl:mixin:APP:allurement.mixins.json:LivingEntityAccessor,pl:mixin:APP:allurement.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:neapolitan.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:814) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.PlayerInteractsEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.PlayerTickMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldDamageMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldDisableMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.PlayerDamagedMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.PlayerDamageShieldInvoker,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:597) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:allurement.mixins.json:AbstractArrowEntityMixin,pl:mixin:A}
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:allurement.mixins.json:AbstractArrowEntityMixin,pl:mixin:A}
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	... 5 more
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
Clipboard copy at: 18 May 2021 18:19:05 -0700
```

Side note, your META-INF/mods.toml still has 1.1.0 listed.

**Comment by OneLemonyBoi** [comment] 2021-05-19 04:36
Duplicate of #34, #29, #33, #36, #37

**Comment by OneLemonyBoi** [comment] 2021-05-19 04:37
please look at closed issues, its not that difficult to do

**Closed by OneLemonyBoi** 2021-05-19 04:36 UTC

**Comment by HellishINC** [comment] 2021-05-19 06:50
Yeah, I should have looked better.

#29 #34 #36 and #37 have nothing to do with this issue though. Nor does saying "fixed in dev" when that is unreleased, not for a show stopping bug like this. Not even the current 'dev' branch fails to build.

**Comment by OneLemonyBoi** [comment] 2021-05-19 17:04
The dev branch is not building due to a caching error on Github's side, not mine. In another issue, I stated that I was releasing a build on Curseforge today. I don't have a bunch of free time so it takes time to fix bugs and get a stable release. Along with that I have to juggle finals and adding new features.
