### ISSUE TITLE
Quantum quarry

### ISSUE THREAD

**Issue by Tenchu98** [OneLemonyBoi/MiniUtilities#54] opened 2021-06-03 14:50 UTC
The quantum quarry has no interface, doesnt accept rf from what I can tell, and is unbreakable in survival.

**Comment by Rachmaninov13** [comment] 2021-06-03 18:10
In multiplayer or singleplayer? If the former, as in #52 .

**Comment by OneLemonyBoi** [comment] 2021-06-04 23:07
yup, duplicate of #52

**Closed by OneLemonyBoi** 2021-06-04 23:07 UTC

**Comment by Tenchu98** [comment] 2021-06-05 01:42
No this was on a MP server.

**Comment by Tenchu98** [comment] 2021-06-05 01:43
> yup, duplicate of #52

Not a duplicate, as this is on a multiplayer server.

**Comment by OneLemonyBoi** [comment] 2021-06-05 16:43
SMP is survival multiplayer, so it is a duplicate
