### ISSUE TITLE
Mini Utilities 1.20.1 - 4.0.0 DEDICATED SERVER CRASH 

### ISSUE THREAD

**Issue by TheWitherlord** [OneLemonyBoi/MiniUtilities#147] opened 2023-07-29 10:24 UTC
**Describe the bug**
The dedicated server crashes when loaded with the mod version above and FORGE version 1.20.1 - 47.1.0

Could this just be the forge version?

**To Reproduce**
1. download mod
2. run dedicated server
3. crash

**Expected behavior**
Load on a dedicated server

https://gist.github.com/TheWitherlord/0b9c2af368cae9ff734d94dadaec0990

**Comment by Fundryi** [comment] 2023-08-06 10:02
Any news on this :(?

**Comment by Fundryi** [comment] 2023-08-25 16:25
Guess this ain't coming any time soon :(?

**Comment by Cguslescop1** [comment] 2023-08-27 16:57
I have the same problem, you have a solution ?

**Comment by Fundryi** [comment] 2023-08-27 16:59
Only dev can fix this sadly :(

**Comment by gardenappl** [comment] 2023-09-05 15:35
Duplicate of #146

**Comment by OneLemonyBoi** [comment] 2024-06-04 21:11
fixed!

**Closed as completed by OneLemonyBoi** 2024-06-04 21:11 UTC
Labels: bug
